# Generated by Django 4.2.7 on 2023-11-17 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MetaDataModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("parentResourceId", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="LogModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("level", models.TextField()),
                ("message", models.TextField()),
                ("resourceId", models.TextField()),
                ("timestamp", models.DateTimeField()),
                ("traceId", models.TextField()),
                ("spanId", models.TextField()),
                ("commit", models.TextField()),
                (
                    "metadata",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="logs.metadatamodel",
                    ),
                ),
            ],
            options={
                "db_table": "log",
            },
        ),
    ]
